//
//  Component.cpp
//  MutexEngine
//
//  Created by Zack Kollar on 6/5/16.
//  Copyright © 2016 Mutex12. All rights reserved.
//

#include "Component.h"

// Get the component name and truncate any leading digits
// generated by the compiler, GCC/Unix bug for runtime class names.

const std::string Component::getComponentName() const {
    // Get the name of the class from the compiler.
    std::string parsedString(typeid(*this).name());
    // Intialize a counter to track soon to be truncated leading digits.
    // PS: This is assuming the class name is less than 256 characters long.
    // ... Which is more than likely!
    char count = 0;
    // Loop over the std::string via index...
    for(char i=0; i < parsedString.length(); ++i) {
        if('0' <= parsedString[i] && parsedString[i] <= '9') {
            // If the char loop value is a digit contitue the loop.
            count++;
        } else {
            // If the char value isn't a digit end the loop...
            // And truncate the string to match edge case class name cases.
            parsedString.erase(0, count);
            // End the loop.
            break;
        }
    }
    // Return the parsed value that's been removed of the leading digits!
    return parsedString;
}